app/views/sub.py
""" All endpoints related to stuff done inside of a particular sub """
import datetime
import time
from flask import Blueprint, redirect, url_for, abort, render_template, request, Response
from flask_login import login_required, current_user
from feedgen.feed import FeedGenerator
from peewee import fn, JOIN
from ..config import config
from ..misc import engine
from ..models import Sub, SubMetadata, SubStylesheet, SubUploads, SubPostComment, SubPost, SubPostPollOption
from ..models import SubPostPollVote, SubPostMetadata, SubFlair, SubLog, User, UserSaved, SubMod, SubBan, SubRule
from ..forms import EditSubFlair, EditSubForm, EditSubCSSForm, EditMod2Form, EditSubRule
from ..forms import BanUserSubForm, CreateSubFlair, PostComment, CreateSubRule
from .. import misc


blueprint = Blueprint('sub', __name__)


@blueprint.route("/<sub>/")
@blueprint.route("/<sub>")
def view_sub(sub):
    """ Here we can view subs """
    if sub.lower() == "all":
        return redirect(url_for('home.all_hot', page=1))

    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    try:
        x = SubMetadata.select().where(SubMetadata.sid == sub.sid)
        x = x.where(SubMetadata.key == 'sort').get()
        x = x.value
    except SubMetadata.DoesNotExist:
        x = 'v'
    if x == 'v_two':
        return redirect(url_for('sub.view_sub_new', sub=sub.name))
    elif x == 'v_three':
        return redirect(url_for('sub.view_sub_top', sub=sub.name))
    else:
        return redirect(url_for('sub.view_sub_hot', sub=sub.name))


@blueprint.route("/<sub>/edit/css")
@login_required
def edit_sub_css(sub):
    """ Here we can edit sub info and settings """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    c = SubStylesheet.get(SubStylesheet.sid == sub.sid)

    form = EditSubCSSForm(css=c.source)
    stor = 0
    ufiles = SubUploads.select().where(SubUploads.sid == sub.sid)
    for uf in ufiles:
        stor += uf.size / 1024

    return engine.get_template('sub/css.html').render({'sub': sub, 'form': form, 'error': False, 'storage': int(stor), 'files': ufiles})


@blueprint.route("/<sub>/edit/flairs")
@login_required
def edit_sub_flairs(sub):
    """ Here we manage the sub's flairs. """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    flairs = SubFlair.select().where(SubFlair.sid == sub.sid).dicts()
    formflairs = []
    for flair in flairs:
        formflairs.append(EditSubFlair(flair=flair['xid'], text=flair['text']))
    return render_template('editflairs.html', sub=sub, flairs=formflairs,
                           createflair=CreateSubFlair())


@blueprint.route("/<sub>/edit/rules")
@login_required
def edit_sub_rules(sub):
    """ Here we manage the sub's rules. """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    rules = SubRule.select().where(SubRule.sid == sub.sid).dicts()
    formrules = []
    for rule in rules:
        formrules.append(EditSubRule(rule=rule['rid'], text=rule['text']))
    return render_template('editrules.html', sub=sub, rules=formrules,
                           createrule=CreateSubRule())


@blueprint.route("/<sub>/edit")
@login_required
def edit_sub(sub):
    """ Here we can edit sub info and settings """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if current_user.is_mod(sub.sid, 1) or current_user.is_admin():
        submeta = misc.metadata_to_dict(SubMetadata.select().where(SubMetadata.sid == sub.sid))
        form = EditSubForm()
        # pre-populate the form.
        form.subsort.data = submeta.get('sort')
        form.sidebar.data = sub.sidebar
        form.title.data = sub.title

        return render_template('editsub.html', sub=sub, editsubform=form, metadata=submeta)
    else:
        abort(403)


@blueprint.route("/<sub>/sublog", defaults={'page': 1})
@blueprint.route("/<sub>/sublog/<int:page>")
def view_sublog(sub, page):
    """ Here we can see a log of mod/admin activity in the sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    subInfo = misc.getSubData(sub.sid)
    if not config.site.force_sublog_public:
        log_is_private = subInfo.get('sublog_private', 0) == '1'

        if log_is_private and not (current_user.is_mod(sub.sid, 1) or current_user.is_admin()):
            abort(404)

    logs = SubLog.select().where(SubLog.sid == sub.sid).order_by(SubLog.lid.desc()).paginate(page, 50)
    return engine.get_template('sub/log.html').render({'sub': sub, 'logs': logs, 'page': page})


@blueprint.route("/<sub>/mods")
@login_required
def edit_sub_mods(sub):
    """ Here we can edit moderators for a sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if current_user.is_mod(sub.sid, 2) or current_user.is_modinv(sub.sid) or current_user.is_admin():
        subdata = misc.getSubData(sub.sid, extra=True)
        subMods = misc.getSubMods(sub.sid)
        modInvites = SubMod.select(User.name, SubMod.power_level).join(User).where((SubMod.sid == sub.sid) & (SubMod.invite == True))
        return render_template('submods.html', sub=sub, subdata=subdata,
                               editmod2form=EditMod2Form(), subMods=subMods, subModInvites=modInvites,
                               banuserform=BanUserSubForm())
    else:
        abort(403)


@blueprint.route("/<sub>/new.rss")
def sub_new_rss(sub):
    """ RSS feed for /sub/new """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    fg = FeedGenerator()
    fg.id(request.url)
    fg.title('New posts from ' + sub.name)
    fg.link(href=request.url_root, rel='alternate')
    fg.link(href=request.url, rel='self')

    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub.sid), 'new', 1).dicts()

    return Response(misc.populate_feed(fg, posts).atom_str(pretty=True), mimetype='application/atom+xml')


@blueprint.route("/<sub>/new", defaults={'page': 1})
@blueprint.route("/<sub>/new/<int:page>")
def view_sub_new(sub, page):
    """ The index page, all posts sorted as most recent posted first """
    if sub.lower() == "all":
        return redirect(url_for('home.all_new', page=1))

    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub['sid']),
                             'new', page).dicts()

    return engine.get_template('sub.html').render({'sub': sub, 'subInfo': misc.getSubData(sub['sid']),
                                                   'posts': posts, 'page': page, 'sort_type': 'sub.view_sub_new',
                                                   'subMods': misc.getSubMods(sub['sid'])})


@blueprint.route("/<sub>/bannedusers")
def view_sub_bans(sub):
    """ See banned users for the sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    user = User.alias()
    created_by = User.alias()
    banned = SubBan.select(user, created_by, SubBan.created, SubBan.reason, SubBan.expires)
    banned = banned.join(user, on=SubBan.uid).switch(SubBan).join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)
    banned = banned.where((SubBan.sid == sub.sid) & ((SubBan.effective == True) & ((SubBan.expires.is_null(True)) | (SubBan.expires > datetime.datetime.utcnow()))))
    banned = banned.order_by(SubBan.created.is_null(True), SubBan.created.desc())

    xbans = SubBan.select(user, created_by, SubBan.created, SubBan.reason, SubBan.expires)
    xbans = xbans.join(user, on=SubBan.uid).switch(SubBan).join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)

    xbans = xbans.where(SubBan.sid == sub.sid)
    xbans = xbans.where((SubBan.effective == False) | ((SubBan.expires.is_null(False)) & (SubBan.expires < datetime.datetime.utcnow())))
    xbans = xbans.order_by(SubBan.created.is_null(True), SubBan.created.desc(), SubBan.expires.asc())

    return engine.get_template('sub/bans.html').render({'sub': sub, 'banned': banned, 'xbans': xbans,
                                                        'banuserform': BanUserSubForm(), 'submods': misc.getSubMods(sub.sid)})


@blueprint.route("/<sub>/top", defaults={'page': 1})
@blueprint.route("/<sub>/top/<int:page>")
def view_sub_top(sub, page):
    """ The index page, /top sorting """
    if sub.lower() == "all":
        return redirect(url_for('home.all_top', page=1))

    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub['sid']),
                             'top', page).dicts()

    return engine.get_template('sub.html').render({'sub': sub, 'subInfo': misc.getSubData(sub['sid']),
                                                   'posts': posts, 'page': page, 'sort_type': 'sub.view_sub_top',
                                                   'subMods': misc.getSubMods(sub['sid'])})


@blueprint.route("/<sub>/hot", defaults={'page': 1})
@blueprint.route("/<sub>/hot/<int:page>")
def view_sub_hot(sub, page):
    """ The index page, /hot sorting """
    if sub.lower() == "all":
        return redirect(url_for('home.all_hot', page=1))

app/views/user.py
""" Profile and settings endpoints """
import time
from peewee import fn, JOIN
from flask import Blueprint, render_template, abort, redirect, url_for
from flask_login import login_required, current_user
from flask_babel import _, Locale
from .. import misc, config
from ..misc import engine
from ..forms import EditUserForm, CreateUserMessageForm, ChangePasswordForm, DeleteAccountForm, PasswordRecoveryForm
from ..forms import PasswordResetForm
from ..models import User, Sub, SubMod, SubPost, SubPostComment, UserSaved, InviteCode, UserMetadata

bp = Blueprint('user', __name__)


@bp.route("/u/<user>")
def view(user):
    """ WIP: View user's profile, posts, comments, badges, etc """
    try:
        user = User.get(fn.lower(User.name) == user.lower())
    except User.DoesNotExist:
        abort(404)

    if user.status == 10:
        abort(404)

    modsquery = SubMod.select(Sub.name, SubMod.power_level).join(Sub).where(
        (SubMod.uid == user.uid) & (SubMod.invite == False))
    owns = [x.sub.name for x in modsquery if x.power_level == 0]
    mods = [x.sub.name for x in modsquery if 1 <= x.power_level <= 2]
    invitecodeinfo = misc.getInviteCodeInfo(user.uid)
    badges = misc.getUserBadges(user.uid)
    pcount = SubPost.select().where(SubPost.uid == user.uid).count()
    ccount = SubPostComment.select().where(SubPostComment.uid == user.uid).count()

    habit = Sub.select(Sub.name, fn.Count(SubPost.pid).alias('count')).join(SubPost, JOIN.LEFT_OUTER,
                                                                            on=(SubPost.sid == Sub.sid))
    habit = habit.where(SubPost.uid == user.uid).group_by(Sub.sid).order_by(fn.Count(SubPost.pid).desc()).limit(10)

    level, xp = misc.get_user_level(user.uid)

    if xp > 0:
        currlv = (level ** 2) * 10
        nextlv = ((level + 1) ** 2) * 10

        required_xp = nextlv - currlv
        progress = ((xp - currlv) / required_xp) * 100
    else:
        progress = 0

    givenScore = misc.getUserGivenScore(user.uid)

    return engine.get_template('user/profile.html').render(
        {'user': user, 'level': level, 'progress': progress, 'postCount': pcount, 'commentCount': ccount,
         'givenScore': givenScore, 'invitecodeinfo': invitecodeinfo, 'badges': badges, 'owns': owns, 'mods': mods, 'habits': habit,
         'msgform': CreateUserMessageForm()})


@bp.route("/u/<user>/posts", defaults={'page': 1})
@bp.route("/u/<user>/posts/<int:page>")
def view_user_posts(user, page):
    """ WIP: View user's recent posts """
    try:
        user = User.get(fn.Lower(User.name) == user.lower())
    except User.DoesNotExist:
        abort(404)
    if user.status == 10:
        abort(404)

    if current_user.is_admin():
        posts = misc.getPostList(misc.postListQueryBase(adminDetail=True).where(User.uid == user.uid),
                                 'new', page).dicts()
    else:
        posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(User.uid == user.uid),
                                 'new', page).dicts()
    return render_template('userposts.html', page=page, sort_type='user.view_user_posts',
                           posts=posts, user=user)


@bp.route("/u/<user>/savedposts", defaults={'page': 1})
@bp.route("/u/<user>/savedposts/<int:page>")
@login_required
def view_user_savedposts(user, page):
    """ WIP: View user's saved posts """
    if current_user.name.lower() == user.lower():
        posts = misc.getPostList(
            misc.postListQueryBase(noAllFilter=True).join(UserSaved, on=(UserSaved.pid == SubPost.pid)).where(
                UserSaved.uid == current_user.uid),
            'new', page).dicts()
        return render_template('userposts.html', page=page,
                               sort_type='user.view_user_savedposts',
                               posts=posts, user=current_user)
    else:
        abort(403)


@bp.route("/u/<user>/comments", defaults={'page': 1})
@bp.route("/u/<user>/comments/<int:page>")
def view_user_comments(user, page):
    """ WIP: View user's recent comments """
    try:
        user = User.get(fn.Lower(User.name) == user.lower())
    except User.DoesNotExist:
        abort(404)
    if user.status == 10:
        abort(404)

    comments = misc.getUserComments(user.uid, page)
    return render_template('usercomments.html', user=user, page=page, comments=comments)


@bp.route("/settings/invite")
@login_required
def invite_codes():
    if not misc.enableInviteCode():
        return redirect('/settings')

    codes = InviteCode.select().where(InviteCode.user == current_user.uid)
    maxcodes = int(misc.getMaxCodes(current_user.uid))
    created = codes.count()
    avail = 0
    if (maxcodes - created) >= 0:
        avail = maxcodes - created
    return engine.get_template('user/settings/invitecode.html').render(
        {'codes': codes, 'created': created, 'max': maxcodes, 'avail': avail,
         'user': User.get(User.uid == current_user.uid)})


@bp.route('/settings/subs')
@login_required
def edit_subs():
    return engine.get_template('user/topbar.html').render({})


@bp.route("/settings")
@login_required
def edit_user():
    styles = 'nostyles' in current_user.prefs
    nsfw = 'nsfw' in current_user.prefs
    exp = 'labrat' in current_user.prefs
    noscroll = 'noscroll' in current_user.prefs
    nochat = 'nochat' in current_user.prefs
    form = EditUserForm(show_nsfw=nsfw,
                        disable_sub_style=styles, experimental=exp,
                        noscroll=noscroll, nochat=nochat, subtheme=current_user.subtheme,
                        language=current_user.language)
    languages = config.app.languages
    form.language.choices = [('', _('Auto detect'))]
    for i in languages:
        form.language.choices.append((i, Locale(*i.split("_")).display_name.capitalize()))
    return engine.get_template('user/settings/preferences.html').render({'edituserform': form, 'user': User.get(User.uid == current_user.uid)})


@bp.route("/settings/password")
@login_required
def edit_password():
    return engine.get_template('user/settings/password.html').render({'form': ChangePasswordForm(), 'user': User.get(User.uid == current_user.uid)})


@bp.route("/settings/delete")
@login_required
def delete_account():
    return engine.get_template('user/settings/delete.html').render({'form': DeleteAccountForm(), 'user': User.get(User.uid == current_user.uid)})


@bp.route("/recover")
def password_recovery():
    """ Endpoint for the password recovery form """
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    form = PasswordRecoveryForm()
    form.cap_key, form.cap_b64 = misc.create_captcha()
    return engine.get_template('user/password_recovery.html').render({'lpform': form})


@bp.route('/reset/<uid>/<key>')
def password_reset(uid, key):
    """ The page that actually resets the password """
    try:
        user = User.get(User.uid == uid)
    except User.DoesNotExist:
        return abort(404)

    try:
        key = UserMetadata.get(
            (UserMetadata.uid == user.uid) & (UserMetadata.key == 'recovery-key') & (UserMetadata.value == key))
        keyExp = UserMetadata.get((UserMetadata.uid == user.uid) & (UserMetadata.key == 'recovery-key-time'))
        expiration = float(keyExp.value)
        if (time.time() - expiration) > 86400:  # 1 day
            # Key is old. remove it and proceed
            key.delete_instance()
            keyExp.delete_instance()
            abort(404)
    except UserMetadata.DoesNotExist:
        return abort(404)

    if current_user.is_authenticated:
        key.delete_instance()
        keyExp.delete_instance()
        return redirect(url_for('home.index'))

    form = PasswordResetForm(key=key.value, user=user.uid)
    return engine.get_template('user/password_reset.html').render({'lpform': form})

app/templates/indexpost.html
<div pid="{{post.pid}}" class="{% if post.deleted != 0 %}deletedpost {% endif %}post">
    <div class="misctainer">
      <div class="votebuttons">
        {% if post.userstatus != 10 and (datetime.datetime.utcnow() - post.posted.replace(tzinfo=None)) < datetime.timedelta(days=60) %}
        <div title="Upvote" class="upvote{%if post.positive == 1%} upvoted{%endif%}" data-pid="{{post.pid}}" data-icon="upvote"></div>
        <div class="score">{{post.score}}</div>
        <div title="Downvote" class="downvote{%if post.positive == 0%} downvoted{%endif%}" data-pid="{{post.pid}}" data-icon="downvote"></div>
        {%endif%}
      </div>
      <div class="thcontainer">
        <a href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}" class="title">
          <div class="thumbnail">
            {% if post.thumbnail != '' and post.link != None %}
              <img src="{{config.storage.thumbnails.url}}{{post.thumbnail}}"/>
            {% elif post.link != None %}
              <span class="placeholder" data-icon="link"></span>
            {%else%}
              <span class="placeholder" data-icon="chat"></span>
            {% endif%}

          </div>
        </a>
      </div>
    </div>
    <div class="pbody">
      <div class="post-heading">
        {% if post.nsfw %}
        <div class="nsfw" alt="Not safe for work">NSFW</div>
        {%endif%}
        {% if post.flair %}<span class="postflair">{{post.flair}}</span>{% endif %}
        {% if post.link == None %}
          <a href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}" class="title">{{post.title}}</a>
        {% else %}
          {% if post.link.startswith('http:') %}<span title="not https" class="p-icon" data-icon="exclaim"></span>{% endif %}
          <a rel="noopener nofollow ugc" href="{{post.link}}" class="title">{{post.title}}</a> <a href="{{url_for('home.all_domain_new', domain=func.getDomain(post.link), page=1)}}" class="domain">({{func.getDomain(post.link)}})</a>
        {% endif %}
      </div>
      <div class="author">
          {% if post.link %}
            {% if func.getDomain(post.link) in ('www.hooktube.com', 'hooktube.com', 'youtube.com', 'www.youtube.com', 'youtu.be', 'gfycat.com', 'vimeo.com', 'vine.co') %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="play"></div></div>
            {% elif func.isImage(post.link) %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="image"></div></div>
            {% elif func.isVideo(post.link) or func.isGifv(post.link) %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="play"></div></div>
            {% endif %}
          {% elif post.content != '' %}
          <div class="expando" data-pid="{{post.pid}}" data-t="txt" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="text"></div></div>
          {% endif %}
        posted <time-ago datetime="{{post.posted.isoformat()}}Z"></time-ago> by
        {% if post.userstatus != 10 %}
          <a class="authorlink" href="{{url_for('user.view', user=post.user)}}">{{post.user}}</a>
        {% endif %}
        {% if sub and post.pid in func.getStickyPid(sub.sid) %}
        - <span class="stick">sticky</span>
        {% endif %}
        {% if not sub %} on
        <a href="{{url_for('sub.view_sub', sub=post.sub)}}">{{post.sub}}</a>
        {%endif%}
      </div>
      <div class="links">
        <a class="comments" href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}">comments {%if post.comments>0%}({{post.comments}}){%endif%}</a>
      </div>
    </div>
</div>

app/templates/usercomments.html
{% extends "layout.html" %}
{% block title %}Comments made by /u/{{user.name}} | {{config.site.lema}}{% endblock %}


{% block sidebar %}
{{ super() }}
<a href="{{url_for('user.view', user=user.name)}}" class="sbm-post pure-button">{{user.name}}</a>
<a href="{{url_for('user.view_user_posts', user=user.name)}}" class="sbm-post pure-button">View posts</a>
<a href="{{url_for('user.view_user_comments', user=user.name)}}" class="sbm-post pure-button">View comments</a>
{% if user.uid == session['user_id'] %}
  <a href="{{url_for('user.view_user_savedposts', user=user.name)}}" class="sbm-post pure-button">View saved posts</a>
{% endif %}
{% endblock %}

{% block content %}
{{ super() }}
<div id="center-container">
  <div class="inbox content">
    <h3>Recent comments</h3>
    <div class="recent">
        {% if comments|length < 1 %}
        <p>
          This user has not commented on anything, yet
        </p>
        {% else %}
        {% for comment in comments %}
        <article id="{{comment.cid}}" data-cid="{{comment.cid}}" class="text-post no-padding comment usercomments">
          <div class="commtitle">
            <span class="title"><a href="{{ url_for('sub.view_post', sub=comment.sub, pid=comment.pid) }}">{{comment.title}}</a></span>
            in <a href="{{ url_for('sub.view_sub', sub=comment.sub) }}">{{comment.sub}}</a>
          </div>
          <div class="commentrow {%if comment.cid == highlight %}highlight{%endif%}" id="comment-{{comment.cid}}">
            <div class="commblock">
              <div class="commenthead">
                  <a href="{{ url_for('user.view', user=user.name) }}" class="poster">{{user.name}}</a> -
                  <b><span class="cscore">{{comment.score}}</span> points</b>
                  <span class="time">
                     <time-ago datetime="{{comment.time.isoformat()}}Z"></time-ago>
                  </span>
                {% if comment.lastedit %}
                  <span class="time edited">
                    *(Edited <time-ago datetime="{{comment.lastedit.isoformat()}}Z"></time-ago>)
                  </span>
                {% endif %}
              </div>
              <div class="content" id="content-{{comment.cid}}">
                {{markdown(comment.content)|safe}}
              </div>
                <div hidden id="sauce-{{comment.cid}}">{{comment.content}}</div>
              <ul class="bottombar links">
                <!-- TODO needs peewee <li><a href="{# url_for('sub.view_perm', sub=sub.name, cid=comment.cid, pid=post.pid) #}">permalink</a></li>-->
                <li><a href="{{url_for('sub.view_perm', sub=comment.sub, pid=comment.pid, cid=comment.cid)}}">permalink</a></li>
                {%if current_user.is_authenticated%}
                  <li><a class="reply-comment" data-pid="{{comment.pid}}" data-to="{{comment.cid}}">reply</a></li>
                  {% if (comment.uid == session['user_id'] or current_user.is_admin()) %}
                    <li><a class="edit-comment" data-cid="{{comment.cid}}">edit</a></li>
                    <li><a class="delete-comment" data-cid="{{comment.cid}}">delete</a></li>
                  {% endif %}
                {%endif%}
                <li><a class="comment-source" data-cid="{{comment.cid}}">source</a></li>
              </ul>
            </div>
          </div>
        </article>
      {% endfor %}
      {% endif %}
    </div>

    {% if page > 1 %}
    <a href="{{url_for('user.view_user_comments', user=user.name, page=(page-1))}}" class="pure-button">prev</a>
    {% endif %}
    {% if comments|length == 20 %}
    <a href="{{url_for('user.view_user_comments', user=user.name, page=(page+1))}}" class="pure-button">next</a>
    {% endif %}

  </div>
</div>
{% endblock %}

app/templates/userposts.html
{% extends "layout.html" %}
{% block title %}Posts from /u/{{user.name}} | {{config.site.lema}}{% endblock %}

{% block sidebar %}
{{ super() }}
<a href="{{url_for('user.view', user=user.name)}}" class="sbm-post pure-button">{{user.name}}</a>
<a href="{{url_for('user.view_user_posts', user=user.name)}}" class="sbm-post pure-button">View posts</a>
<a href="{{url_for('user.view_user_comments', user=user.name)}}" class="sbm-post pure-button">View comments</a>
{% if user.uid == current_user.uid %}
  <a href="{{url_for('user.view_user_savedposts', user=user.name)}}" class="sbm-post pure-button">View saved posts</a>
{% endif %}
{% endblock %}

{% block content %}
{{ super() }}
{% if sort_type == 'user.view_user_posts' %}
  <h3>Recent posts</h3>
{% else %}
  <h3>Saved posts</h3>
{% endif %}
{% if not posts %}
  <h3>There are no posts here, yet.</h3>
{% endif %}

<div class="alldaposts">
{% for post in posts %}
  {% include "indexpost.html" %}
{%endfor%}
</div>

{% if page > 1 %}
  <a href="{{url_for(sort_type, page=(page-1), user=user.name)}}" class="pure-button">prev</a>
{% endif %}
{% if posts|length == 25 %}
  <a href="{{url_for(sort_type, page=(page+1), user=user.name)}}" class="pure-button">next</a>
{% endif %}
{% endblock %}